# Generated by Django 6.0.4 on 2026-05-05 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonregistration',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Developer, Designer, Project Manager', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IdeaJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='hackathon.ideasubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'idea')},
            },
        ),
    ]
