# Generated by Django 6.0.4 on 2026-05-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_hackathonregistration_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideasubmission',
            old_name='target_tools',
            new_name='suggested_tools',
        ),
        migrations.RemoveField(
            model_name='ideasubmission',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ideasubmission',
            name='idea_description',
        ),
        migrations.RemoveField(
            model_name='ideasubmission',
            name='team_name',
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='problem_statement',
            field=models.TextField(default='Describe the problem...'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='proposed_title',
            field=models.CharField(default='Untitled Proposal', max_length=255),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
