# Generated by Django 6.0.4 on 2026-05-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_rename_target_tools_ideasubmission_suggested_tools_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDGCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which to display categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'GDG Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GDGGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL friendly name (e.g., 'getting-started-with-gcp')", max_length=255, unique=True)),
                ('content', models.TextField(help_text='Markdown content for the guide')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display guides within a category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='hackathon.gdgcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
