# Generated by Django 6.0.4 on 2026-05-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_gdgcategory_gdgguide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonevent',
            name='description',
            field=models.TextField(blank=True, default='Hackathon Event'),
        ),
        migrations.AddField(
            model_name='hackathonevent',
            name='judging_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='progress_status',
            field=models.CharField(default='Just Started', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='hackathon.hackathonevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
